# -*- coding: utf-8 -*-
"""Face_recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E8zQNRwSZOozv_4lpm46vcV_EYhsgA8J
"""

!pip install deepface

from deepface import DeepFace
import cv2
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

img_path ='your img path'
img = cv2.imread(img_path)
plt.imshow(img[:,:,::-1])

face = DeepFace.detectFace(img_path, target_size =(224,224),detector_backend ='opencv')
plt.imshow(face)

objs = DeepFace.analyze(img_path,
        actions = ['age', 'gender', 'race', 'emotion']
)
age = objs[0]['age']
emotion = objs[0]['dominant_emotion']
race = objs[0]['dominant_race']
gender = objs[0]['dominant_gender']
print('\n emosi  : ',emotion)
print('ras  : ',race)
print('jenis Kelamin : ',gender)
print('umur : ',age)